version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    restart: always
    ports:
    - "8080:8080"
    depends_on:
    - redis
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules
  redis:
    image: redis:latest
    container_name: redis_container
    restart: 'always'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local